### ISSUE TITLE
Potential for Panic in `From` Implementation

### ISSUE THREAD

**Issue by ultrabear** [GnomedDev/small-fixed-array#2]
in the folowing code: https://github.com/GnomedDev/small-fixed-array/blob/101610c061830127811ed3414de1794996a20eb0/src/non_empty_array.rs#L42

two potential panics can occur, one of which is "impossible" as far as the public api is concerned, because only non empty slices will ever call this, but an overflow also immediately panics, this is a poor behavior in the first place (error recovery should be given to users of the crate), however it is also [**against the From/Into implementation guidelines**](https://doc.rust-lang.org/std/convert/trait.From.html): 
`Note: This trait must not fail. The From trait is intended for perfect conversions. If the conversion can fail or is not perfect, use TryFrom.`

**Comment by GnomedDev** [comment]
I personally see this as similar to the panics on allocation failure or similar, it isn't exactly useful for most users to have to deal with "Yes I'm not going to fill this string with 2gb of data", but I'd like to see another opinion other than "but the trait docs say".

**Comment by GnomedDev** [comment]
I've fixed this by truncating array lengths and triggering a log/tracing warning in `From` implementations, and removing `From` where this is not possible.
