### ISSUE TITLE
Add `From<&FixedString> for Cow<str>`

### ISSUE THREAD

**Issue by DPlayer234** [GnomedDev/small-fixed-array#3]
Trying to pass a reference to a `FixedString` into a borrowed `Cow<str>` currently fails to compile due to the missing appropriate impl.

This impl should be added for parity with `String`:

```rust
impl<'a, LenT: ValidLength> From<&'a FixedString<LenT>> for Cow<'a, str>
```

Without this impl, there are errors when moving from `String` to `FixedString` in places where they are passed by reference to an `impl Into<Cow<'_, str>>` parameter.

This can be worked around by calling `.as_str()` instead of taking a reference, but it requires more code changes.

**Comment by GnomedDev** [comment]
Implemented, as well as for FixedArray.
